site_name: Bitcoin Cash Reference Documentation
docs_dir: docs
theme:
    name: mkdocs
    custom_dir: custom_theme
nav:
    - Home: index.md
    - Glossary: glossary.md
    - Protocol: protocol.md
plugins:
    - markdownmermaid
    - search
extra_javascript:
    - https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js
